version: '3.4'

services:
  ms-datasource-feeder:
    build:
      context: .
    image: airquality/ms-datasource-feeder:0.1
    networks:
      - isolated    

  influx:
    container_name: influxDB
    image: influxdb:2.0
    volumes:
      - influxdb2:/var/lib/influxdb2
    ports:
      - "8086:8086"
    networks:
      - isolated

volumes:
  influxdb2:

networks:
  isolated: